name: CI

on:
  push:
    branches: [ master ]

  schedule:
    - cron:  '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v1

    - name: Install Futhark
      run: |
          wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
          tar xf futhark-nightly-linux-x86_64.tar.xz
          (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)
          echo "$HOME/.local/bin" >> $GITHUB_PATH

    - uses: actions/cache@v2
      name: Cache
      with:
        path: |
          pkgs
        key: ${{ runner.os }}-pkgs

    - name: Prepare
      run: |
        git checkout pkgs/style.css # Might be overwritten by cache.
        go build

    - name: Generate docs
      run: |
        go run futhark-docbot.go pkgpaths.txt

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSHKEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Upload docs
      run: |
        rsync -r --delete-after --quiet $PWD/pkgs futhark@sigkill.dk:/var/www/htdocs/futhark-lang.org/
